// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Golubets, do not edit directly.
// See also: https://pub.dev/packages/golubets
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, omit_local_variable_types, omit_obvious_local_variable_types

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

<<<<<<< HEAD:packages/golubets/example/app/lib/src/messages.g.dart
enum Code {
  one,
  two,
}
=======
int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum Code { one, two }
>>>>>>> filtered-upstream/main:packages/pigeon/example/app/lib/src/messages.g.dart

class MessageData {
  MessageData({
    this.name = 'Golub',
    this.description = 'Example description',
    this.code = Code.one,
    this.data = const <String, String>{
      'hello': 'world',
      'lorem': 'ipsum',
      'golubets': 'rocks',
    },
  });

  String? name;

  String? description;

  Code code;

  Map<String, String> data;

  List<Object?> _toList() {
    return <Object?>[
      name,
      description,
      code,
      data,
    ];
  }

  Object encode() {
    return _toList();
  }

  static MessageData decode(Object result) {
    result as List<Object?>;
    return MessageData(
      name: result[0] as String?,
      description: result[1] as String?,
      code: result[2]! as Code,
      data: (result[3]! as Map<Object?, Object?>).cast<String, String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MessageData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(name, other.name) &&
        _deepEquals(description, other.description) &&
        _deepEquals(code, other.code) &&
        _deepEquals(data, other.data);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class _GolubetsCodec extends StandardMessageCodec {
  const _GolubetsCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is Code) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is MessageData) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : Code.values[value];
      case 130:
        return MessageData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class ExampleHostApi {
  /// Constructor for [ExampleHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ExampleHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : golubetsVar_binaryMessenger = binaryMessenger,
       golubetsVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? golubetsVar_binaryMessenger;

  static const MessageCodec<Object?> golubetsChannelCodec = _GolubetsCodec();

  final String golubetsVar_messageChannelSuffix;

  Future<String> getHostLanguage() async {
    final golubetsVar_channelName =
        'dev.bayori.golubets.golubets_example_package.ExampleHostApi.getHostLanguage$golubetsVar_messageChannelSuffix';
    final golubetsVar_channel = BasicMessageChannel<Object?>(
      golubetsVar_channelName,
      golubetsChannelCodec,
      binaryMessenger: golubetsVar_binaryMessenger,
    );
    final Future<Object?> golubetsVar_sendFuture = golubetsVar_channel.send(
      null,
    );
    final golubetsVar_replyList =
        await golubetsVar_sendFuture as List<Object?>?;

    final Object? golubetsVar_replyValue = _extractReplyValueOrThrow(
      golubetsVar_replyList,
      golubetsVar_channelName,
      isNullValid: false,
    );
    return golubetsVar_replyValue! as String;
  }

  Future<int> add(int a, int b) async {
    final golubetsVar_channelName =
        'dev.bayori.golubets.golubets_example_package.ExampleHostApi.add$golubetsVar_messageChannelSuffix';
    final golubetsVar_channel = BasicMessageChannel<Object?>(
      golubetsVar_channelName,
      golubetsChannelCodec,
      binaryMessenger: golubetsVar_binaryMessenger,
    );
    final Future<Object?> golubetsVar_sendFuture = golubetsVar_channel.send(
      <Object?>[a, b],
    );
    final golubetsVar_replyList =
        await golubetsVar_sendFuture as List<Object?>?;

    final Object? golubetsVar_replyValue = _extractReplyValueOrThrow(
      golubetsVar_replyList,
      golubetsVar_channelName,
      isNullValid: false,
    );
    return golubetsVar_replyValue! as int;
  }

  Future<bool> sendMessage(MessageData message) async {
    final golubetsVar_channelName =
        'dev.bayori.golubets.golubets_example_package.ExampleHostApi.sendMessage$golubetsVar_messageChannelSuffix';
    final golubetsVar_channel = BasicMessageChannel<Object?>(
      golubetsVar_channelName,
      golubetsChannelCodec,
      binaryMessenger: golubetsVar_binaryMessenger,
    );
    final Future<Object?> golubetsVar_sendFuture = golubetsVar_channel.send(
      <Object?>[message],
    );
    final golubetsVar_replyList =
        await golubetsVar_sendFuture as List<Object?>?;

    final Object? golubetsVar_replyValue = _extractReplyValueOrThrow(
      golubetsVar_replyList,
      golubetsVar_channelName,
      isNullValid: false,
    );
    return golubetsVar_replyValue! as bool;
  }

  Future<bool> sendMessageModernAsync(MessageData message) async {
    final golubetsVar_channelName =
        'dev.bayori.golubets.golubets_example_package.ExampleHostApi.sendMessageModernAsync$golubetsVar_messageChannelSuffix';
    final golubetsVar_channel = BasicMessageChannel<Object?>(
      golubetsVar_channelName,
      golubetsChannelCodec,
      binaryMessenger: golubetsVar_binaryMessenger,
    );
    final Future<Object?> golubetsVar_sendFuture = golubetsVar_channel.send(
      <Object?>[message],
    );
    final golubetsVar_replyList =
        await golubetsVar_sendFuture as List<Object?>?;

    final Object? golubetsVar_replyValue = _extractReplyValueOrThrow(
      golubetsVar_replyList,
      golubetsVar_channelName,
      isNullValid: false,
    );
    return golubetsVar_replyValue! as bool;
  }

  Future<bool> sendMessageModernAsyncThrows(MessageData message) async {
    final golubetsVar_channelName =
        'dev.bayori.golubets.golubets_example_package.ExampleHostApi.sendMessageModernAsyncThrows$golubetsVar_messageChannelSuffix';
    final golubetsVar_channel = BasicMessageChannel<Object?>(
      golubetsVar_channelName,
      golubetsChannelCodec,
      binaryMessenger: golubetsVar_binaryMessenger,
    );
    final Future<Object?> golubetsVar_sendFuture = golubetsVar_channel.send(
      <Object?>[message],
    );
    final golubetsVar_replyList =
        await golubetsVar_sendFuture as List<Object?>?;

    final Object? golubetsVar_replyValue = _extractReplyValueOrThrow(
      golubetsVar_replyList,
      golubetsVar_channelName,
      isNullValid: false,
    );
    return golubetsVar_replyValue! as bool;
  }
}

abstract class MessageFlutterApi {
  static const MessageCodec<Object?> golubetsChannelCodec = _GolubetsCodec();

  String flutterMethod(String? aString);

  static void setUp(
    MessageFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final golubetsVar_channel = BasicMessageChannel<Object?>(
        'dev.bayori.golubets.golubets_example_package.MessageFlutterApi.flutterMethod$messageChannelSuffix',
        golubetsChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        golubetsVar_channel.setMessageHandler(null);
      } else {
        golubetsVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String? arg_aString = args[0] as String?;
          try {
            final String output = api.flutterMethod(arg_aString);
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
