// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Golubets, do not edit directly.
// See also: https://pub.dev/packages/golubets
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    return a.length == b.length &&
        a.entries.every(
          (MapEntry<Object?, Object?> entry) =>
              (b as Map<Object?, Object?>).containsKey(entry.key) &&
              _deepEquals(entry.value, b[entry.key]),
        );
  }
  return a == b;
}

enum Code {
  one,
  two,
}

class MessageData {
  MessageData({
    this.name = 'Golub',
    this.description = 'Example description',
    this.code = Code.one,
    this.data = const <String, String>{
      'hello': 'world',
      'lorem': 'ipsum',
      'golubets': 'rocks',
    },
  });

  String? name;

  String? description;

  Code code;

  Map<String, String> data;

  List<Object?> _toList() {
    return <Object?>[
      name,
      description,
      code,
      data,
    ];
  }

  Object encode() {
    return _toList();
  }

  static MessageData decode(Object result) {
    result as List<Object?>;
    return MessageData(
      name: result[0] as String?,
      description: result[1] as String?,
      code: result[2]! as Code,
      data: (result[3] as Map<Object?, Object?>?)!.cast<String, String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MessageData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class _GolubetsCodec extends StandardMessageCodec {
  const _GolubetsCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is Code) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is MessageData) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : Code.values[value];
      case 130:
        return MessageData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class ExampleHostApi {
  /// Constructor for [ExampleHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ExampleHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : golubetsVar_binaryMessenger = binaryMessenger,
       golubetsVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? golubetsVar_binaryMessenger;

  static const MessageCodec<Object?> golubetsChannelCodec = _GolubetsCodec();

  final String golubetsVar_messageChannelSuffix;

  Future<String> getHostLanguage() async {
    final String golubetsVar_channelName =
        'dev.bayori.golubets.golubets_example_package.ExampleHostApi.getHostLanguage$golubetsVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> golubetsVar_channel =
        BasicMessageChannel<Object?>(
          golubetsVar_channelName,
          golubetsChannelCodec,
          binaryMessenger: golubetsVar_binaryMessenger,
        );
    final Future<Object?> golubetsVar_sendFuture = golubetsVar_channel.send(
      null,
    );
    final List<Object?>? golubetsVar_replyList =
        await golubetsVar_sendFuture as List<Object?>?;
    if (golubetsVar_replyList == null) {
      throw _createConnectionError(golubetsVar_channelName);
    } else if (golubetsVar_replyList.length > 1) {
      throw PlatformException(
        code: golubetsVar_replyList[0]! as String,
        message: golubetsVar_replyList[1] as String?,
        details: golubetsVar_replyList[2],
      );
    } else if (golubetsVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (golubetsVar_replyList[0] as String?)!;
    }
  }

  Future<int> add(int a, int b) async {
    final String golubetsVar_channelName =
        'dev.bayori.golubets.golubets_example_package.ExampleHostApi.add$golubetsVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> golubetsVar_channel =
        BasicMessageChannel<Object?>(
          golubetsVar_channelName,
          golubetsChannelCodec,
          binaryMessenger: golubetsVar_binaryMessenger,
        );
    final Future<Object?> golubetsVar_sendFuture = golubetsVar_channel.send(
      <Object?>[a, b],
    );
    final List<Object?>? golubetsVar_replyList =
        await golubetsVar_sendFuture as List<Object?>?;
    if (golubetsVar_replyList == null) {
      throw _createConnectionError(golubetsVar_channelName);
    } else if (golubetsVar_replyList.length > 1) {
      throw PlatformException(
        code: golubetsVar_replyList[0]! as String,
        message: golubetsVar_replyList[1] as String?,
        details: golubetsVar_replyList[2],
      );
    } else if (golubetsVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (golubetsVar_replyList[0] as int?)!;
    }
  }

  Future<bool> sendMessage(MessageData message) async {
    final String golubetsVar_channelName =
        'dev.bayori.golubets.golubets_example_package.ExampleHostApi.sendMessage$golubetsVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> golubetsVar_channel =
        BasicMessageChannel<Object?>(
          golubetsVar_channelName,
          golubetsChannelCodec,
          binaryMessenger: golubetsVar_binaryMessenger,
        );
    final Future<Object?> golubetsVar_sendFuture = golubetsVar_channel.send(
      <Object?>[message],
    );
    final List<Object?>? golubetsVar_replyList =
        await golubetsVar_sendFuture as List<Object?>?;
    if (golubetsVar_replyList == null) {
      throw _createConnectionError(golubetsVar_channelName);
    } else if (golubetsVar_replyList.length > 1) {
      throw PlatformException(
        code: golubetsVar_replyList[0]! as String,
        message: golubetsVar_replyList[1] as String?,
        details: golubetsVar_replyList[2],
      );
    } else if (golubetsVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (golubetsVar_replyList[0] as bool?)!;
    }
  }

  Future<bool> sendMessageModernAsync(MessageData message) async {
    final String golubetsVar_channelName =
        'dev.bayori.golubets.golubets_example_package.ExampleHostApi.sendMessageModernAsync$golubetsVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> golubetsVar_channel =
        BasicMessageChannel<Object?>(
          golubetsVar_channelName,
          golubetsChannelCodec,
          binaryMessenger: golubetsVar_binaryMessenger,
        );
    final Future<Object?> golubetsVar_sendFuture = golubetsVar_channel.send(
      <Object?>[message],
    );
    final List<Object?>? golubetsVar_replyList =
        await golubetsVar_sendFuture as List<Object?>?;
    if (golubetsVar_replyList == null) {
      throw _createConnectionError(golubetsVar_channelName);
    } else if (golubetsVar_replyList.length > 1) {
      throw PlatformException(
        code: golubetsVar_replyList[0]! as String,
        message: golubetsVar_replyList[1] as String?,
        details: golubetsVar_replyList[2],
      );
    } else if (golubetsVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (golubetsVar_replyList[0] as bool?)!;
    }
  }

  Future<bool> sendMessageModernAsyncThrows(MessageData message) async {
    final String golubetsVar_channelName =
        'dev.bayori.golubets.golubets_example_package.ExampleHostApi.sendMessageModernAsyncThrows$golubetsVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> golubetsVar_channel =
        BasicMessageChannel<Object?>(
          golubetsVar_channelName,
          golubetsChannelCodec,
          binaryMessenger: golubetsVar_binaryMessenger,
        );
    final Future<Object?> golubetsVar_sendFuture = golubetsVar_channel.send(
      <Object?>[message],
    );
    final List<Object?>? golubetsVar_replyList =
        await golubetsVar_sendFuture as List<Object?>?;
    if (golubetsVar_replyList == null) {
      throw _createConnectionError(golubetsVar_channelName);
    } else if (golubetsVar_replyList.length > 1) {
      throw PlatformException(
        code: golubetsVar_replyList[0]! as String,
        message: golubetsVar_replyList[1] as String?,
        details: golubetsVar_replyList[2],
      );
    } else if (golubetsVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (golubetsVar_replyList[0] as bool?)!;
    }
  }
}

abstract class MessageFlutterApi {
  static const MessageCodec<Object?> golubetsChannelCodec = _GolubetsCodec();

  String flutterMethod(String? aString);

  static void setUp(
    MessageFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final BasicMessageChannel<Object?>
      golubetsVar_channel = BasicMessageChannel<Object?>(
        'dev.bayori.golubets.golubets_example_package.MessageFlutterApi.flutterMethod$messageChannelSuffix',
        golubetsChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        golubetsVar_channel.setMessageHandler(null);
      } else {
        golubetsVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.bayori.golubets.golubets_example_package.MessageFlutterApi.flutterMethod was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_aString = (args[0] as String?);
          try {
            final String output = api.flutterMethod(arg_aString);
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
