// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file specifically tests the test GolubetsInstanceManager generated by core_tests.

import 'package:flutter_test/flutter_test.dart';
import 'package:leak_tracker/leak_tracker.dart';
import 'package:shared_test_plugin_code/src/generated/proxy_api_tests.gen.dart';

void main() {
  group('InstanceManager', () {
    test('addHostCreatedInstance', () {
<<<<<<< HEAD:packages/golubets/platform_tests/shared_test_plugin_code/test/instance_manager_test.dart
      final instanceManager = GolubetsInstanceManager(
        onWeakReferenceRemoved: (_) {},
      );
=======
      final instanceManager = PigeonInstanceManager(onWeakReferenceRemoved: (_) {});
>>>>>>> filtered-upstream/main:packages/pigeon/platform_tests/shared_test_plugin_code/test/instance_manager_test.dart

      final object = CopyableObject(
        golubets_instanceManager: instanceManager,
      );

      instanceManager.addHostCreatedInstance(object, 0);

      expect(instanceManager.getIdentifier(object), 0);
      expect(instanceManager.getInstanceWithWeakReference(0), isA<CopyableObject>());
    });

    test('addHostCreatedInstance prevents already used objects and ids', () {
<<<<<<< HEAD:packages/golubets/platform_tests/shared_test_plugin_code/test/instance_manager_test.dart
      final instanceManager = GolubetsInstanceManager(
        onWeakReferenceRemoved: (_) {},
      );
=======
      final instanceManager = PigeonInstanceManager(onWeakReferenceRemoved: (_) {});
>>>>>>> filtered-upstream/main:packages/pigeon/platform_tests/shared_test_plugin_code/test/instance_manager_test.dart

      final object = CopyableObject(
        golubets_instanceManager: instanceManager,
      );

      instanceManager.addHostCreatedInstance(object, 0);

      expect(() => instanceManager.addHostCreatedInstance(object, 0), throwsAssertionError);

      expect(
        () => instanceManager.addHostCreatedInstance(
          CopyableObject(golubets_instanceManager: instanceManager),
          0,
        ),
        throwsAssertionError,
      );
    });

    test('addFlutterCreatedInstance', () {
<<<<<<< HEAD:packages/golubets/platform_tests/shared_test_plugin_code/test/instance_manager_test.dart
      final instanceManager = GolubetsInstanceManager(
        onWeakReferenceRemoved: (_) {},
      );
=======
      final instanceManager = PigeonInstanceManager(onWeakReferenceRemoved: (_) {});
>>>>>>> filtered-upstream/main:packages/pigeon/platform_tests/shared_test_plugin_code/test/instance_manager_test.dart

      final object = CopyableObject(
        golubets_instanceManager: instanceManager,
      );

      instanceManager.addDartCreatedInstance(object);

      final int? instanceId = instanceManager.getIdentifier(object);
      expect(instanceId, isNotNull);
      expect(instanceManager.getInstanceWithWeakReference(instanceId!), object);
    });

    test('removeWeakReference', () {
      int? weakInstanceId;
      final instanceManager = GolubetsInstanceManager(
        onWeakReferenceRemoved: (int instanceId) {
          weakInstanceId = instanceId;
        },
      );

      final object = CopyableObject(
        golubets_instanceManager: instanceManager,
      );

      instanceManager.addHostCreatedInstance(object, 0);

      expect(instanceManager.removeWeakReference(object), 0);
      expect(instanceManager.getInstanceWithWeakReference(0), isA<CopyableObject>());
      expect(weakInstanceId, 0);
    });

    test('removeWeakReference removes only weak reference', () {
<<<<<<< HEAD:packages/golubets/platform_tests/shared_test_plugin_code/test/instance_manager_test.dart
      final instanceManager = GolubetsInstanceManager(
        onWeakReferenceRemoved: (_) {},
      );
=======
      final instanceManager = PigeonInstanceManager(onWeakReferenceRemoved: (_) {});
>>>>>>> filtered-upstream/main:packages/pigeon/platform_tests/shared_test_plugin_code/test/instance_manager_test.dart

      final object = CopyableObject(
        golubets_instanceManager: instanceManager,
      );

      instanceManager.addHostCreatedInstance(object, 0);

      expect(instanceManager.removeWeakReference(object), 0);
      final CopyableObject copy = instanceManager.getInstanceWithWeakReference(0)!;
      expect(identical(object, copy), isFalse);
    });

    test('remove', () {
<<<<<<< HEAD:packages/golubets/platform_tests/shared_test_plugin_code/test/instance_manager_test.dart
      final instanceManager = GolubetsInstanceManager(
        onWeakReferenceRemoved: (_) {},
      );
=======
      final instanceManager = PigeonInstanceManager(onWeakReferenceRemoved: (_) {});
>>>>>>> filtered-upstream/main:packages/pigeon/platform_tests/shared_test_plugin_code/test/instance_manager_test.dart

      final object = CopyableObject(
        golubets_instanceManager: instanceManager,
      );

      instanceManager.addHostCreatedInstance(object, 0);
      instanceManager.removeWeakReference(object);
      expect(instanceManager.remove(0), isA<CopyableObject>());
      expect(instanceManager.containsIdentifier(0), isFalse);
    });

    test('remove throws AssertionError if weak reference still exists', () {
<<<<<<< HEAD:packages/golubets/platform_tests/shared_test_plugin_code/test/instance_manager_test.dart
      final instanceManager = GolubetsInstanceManager(
        onWeakReferenceRemoved: (_) {},
      );
=======
      final instanceManager = PigeonInstanceManager(onWeakReferenceRemoved: (_) {});
>>>>>>> filtered-upstream/main:packages/pigeon/platform_tests/shared_test_plugin_code/test/instance_manager_test.dart

      final object = CopyableObject(
        golubets_instanceManager: instanceManager,
      );

      instanceManager.addDartCreatedInstance(object);
      expect(() => instanceManager.remove(0), throwsAssertionError);
    });

    test('getInstance can add a new weak reference', () {
<<<<<<< HEAD:packages/golubets/platform_tests/shared_test_plugin_code/test/instance_manager_test.dart
      final instanceManager = GolubetsInstanceManager(
        onWeakReferenceRemoved: (_) {},
      );
=======
      final instanceManager = PigeonInstanceManager(onWeakReferenceRemoved: (_) {});
>>>>>>> filtered-upstream/main:packages/pigeon/platform_tests/shared_test_plugin_code/test/instance_manager_test.dart

      final object = CopyableObject(
        golubets_instanceManager: instanceManager,
      );

      instanceManager.addHostCreatedInstance(object, 0);
      instanceManager.removeWeakReference(object);

      final CopyableObject newWeakCopy = instanceManager.getInstanceWithWeakReference(0)!;
      expect(identical(object, newWeakCopy), isFalse);
    });

<<<<<<< HEAD:packages/golubets/platform_tests/shared_test_plugin_code/test/instance_manager_test.dart
    test(
      'addDartCreatedInstance should add finalizer to original object',
      () async {
        var weakReferencedRemovedCalled = false;
        final instanceManager = GolubetsInstanceManager(
          onWeakReferenceRemoved: (_) {
            weakReferencedRemovedCalled = true;
          },
        );

        CopyableObject? object = CopyableObject(
          golubets_instanceManager: instanceManager,
        );
=======
    test('addDartCreatedInstance should add finalizer to original object', () async {
      var weakReferencedRemovedCalled = false;
      final instanceManager = PigeonInstanceManager(
        onWeakReferenceRemoved: (_) {
          weakReferencedRemovedCalled = true;
        },
      );

      CopyableObject? object = CopyableObject(pigeon_instanceManager: instanceManager);
>>>>>>> filtered-upstream/main:packages/pigeon/platform_tests/shared_test_plugin_code/test/instance_manager_test.dart

      instanceManager.addDartCreatedInstance(object);

      object = null;
      await forceGC(fullGcCycles: 2);

      expect(weakReferencedRemovedCalled, isTrue);
    });

<<<<<<< HEAD:packages/golubets/platform_tests/shared_test_plugin_code/test/instance_manager_test.dart
    test(
      'addHostCreatedInstance should not add finalizer to original object',
      () async {
        var weakReferencedRemovedCalled = false;
        final instanceManager = GolubetsInstanceManager(
          onWeakReferenceRemoved: (_) {
            weakReferencedRemovedCalled = true;
          },
        );

        CopyableObject? object = CopyableObject(
          golubets_instanceManager: instanceManager,
        );
=======
    test('addHostCreatedInstance should not add finalizer to original object', () async {
      var weakReferencedRemovedCalled = false;
      final instanceManager = PigeonInstanceManager(
        onWeakReferenceRemoved: (_) {
          weakReferencedRemovedCalled = true;
        },
      );

      CopyableObject? object = CopyableObject(pigeon_instanceManager: instanceManager);
>>>>>>> filtered-upstream/main:packages/pigeon/platform_tests/shared_test_plugin_code/test/instance_manager_test.dart

      instanceManager.addHostCreatedInstance(object, 0);

      object = null;
      await forceGC(fullGcCycles: 2);

      expect(weakReferencedRemovedCalled, isFalse);
    });

    testWidgets('instantiating default InstanceManager does not make a message call', (
      WidgetTester tester,
    ) async {
      var messageCallMade = false;
      TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger.allMessagesHandler =
          (_, _, _) {
            messageCallMade = true;
            return null;
          };

<<<<<<< HEAD:packages/golubets/platform_tests/shared_test_plugin_code/test/instance_manager_test.dart
        // Initialize default InstanceManager
        // ignore: unnecessary_statements
        GolubetsInstanceManager.instance;
=======
      // Initialize default InstanceManager
      // ignore: unnecessary_statements
      PigeonInstanceManager.instance;
>>>>>>> filtered-upstream/main:packages/pigeon/platform_tests/shared_test_plugin_code/test/instance_manager_test.dart

      expect(messageCallMade, isFalse);
    });

    testWidgets(
      'default InstanceManager does not make message call when weak reference is removed',
      (WidgetTester tester) async {
        var messageCallMade = false;
        TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger.allMessagesHandler =
            (_, _, _) {
              messageCallMade = true;
              return null;
            };

<<<<<<< HEAD:packages/golubets/platform_tests/shared_test_plugin_code/test/instance_manager_test.dart
        final GolubetsInstanceManager instanceManager =
            GolubetsInstanceManager.instance;
=======
        final PigeonInstanceManager instanceManager = PigeonInstanceManager.instance;
>>>>>>> filtered-upstream/main:packages/pigeon/platform_tests/shared_test_plugin_code/test/instance_manager_test.dart

        final int identifier = instanceManager.addDartCreatedInstance(CopyableObject());
        instanceManager.onWeakReferenceRemoved(identifier);

        expect(messageCallMade, isFalse);
      },
    );
  });
}

class CopyableObject extends GolubetsInternalProxyApiBaseClass {
  // ignore: non_constant_identifier_names
  CopyableObject({super.golubets_instanceManager});

  @override
  // ignore: non_constant_identifier_names
  CopyableObject golubets_copy() {
    return CopyableObject(golubets_instanceManager: golubets_instanceManager);
  }
}
