// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Golubets, do not edit directly.
// See also: https://pub.dev/packages/golubets

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsEventChannelMessages(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashEventChannelMessages(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8_0000_0000_0000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsEventChannelMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsEventChannelMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsEventChannelMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsEventChannelMessages(lhsKey, rhsKey) {
          if deepEqualsEventChannelMessages(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsEventChannelMessages(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
<<<<<<< HEAD:packages/golubets/example/app/ios/Runner/EventChannelMessages.g.swift
    // Any other type shouldn't be able to be used with golubetsets. File an issue if you find this to be untrue.
=======
>>>>>>> filtered-upstream/main:packages/pigeon/example/app/ios/Runner/EventChannelMessages.g.swift
    return false
  }
}

func deepHashEventChannelMessages(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashEventChannelMessages(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashEventChannelMessages(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashEventChannelMessages(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashEventChannelMessages(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashEventChannelMessages(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}

/// Generated class from Golubets that represents data sent in messages.
public enum PlatformEvent: Hashable {
  case intEvent(
    data: Int64
  )

  case stringEvent(
    data: String
  )

  case emptyEvent

  internal static func fromListIntEvent(_ list: [Any?]) -> PlatformEvent? {
    let data = list[0] as! Int64

    return .intEvent(
      data: data
    )
  }

  internal static func fromListStringEvent(_ list: [Any?]) -> PlatformEvent? {
    let data = list[0] as! String

    return .stringEvent(
      data: data
    )
  }
<<<<<<< HEAD:packages/golubets/example/app/ios/Runner/EventChannelMessages.g.swift

  internal static func fromListEmptyEvent(_ list: [Any?]) -> PlatformEvent? {
    return .emptyEvent
  }

  public func toList() -> [Any?] {
    switch self {
    case .intEvent(
      let data
    ):
      return [
        data
      ]
    case .stringEvent(
      let data
    ):
      return [
        data
      ]
    case .emptyEvent:
      return []
    }
  }
  public static func == (lhs: PlatformEvent, rhs: PlatformEvent) -> Bool {
    return deepEqualsEventChannelMessages(lhs.toList(), rhs.toList())
  }
  public func hash(into hasher: inout Hasher) {
    deepHashEventChannelMessages(value: toList(), hasher: &hasher)
  }
}

private class EventChannelMessagesGolubetsCodecReader: FlutterStandardReader {
=======
  static func == (lhs: IntEvent, rhs: IntEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsEventChannelMessages(lhs.data, rhs.data)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("IntEvent")
    deepHashEventChannelMessages(value: data, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct StringEvent: PlatformEvent {
  var data: String

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> StringEvent? {
    let data = pigeonVar_list[0] as! String

    return StringEvent(
      data: data
    )
  }
  func toList() -> [Any?] {
    return [
      data
    ]
  }
  static func == (lhs: StringEvent, rhs: StringEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsEventChannelMessages(lhs.data, rhs.data)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("StringEvent")
    deepHashEventChannelMessages(value: data, hasher: &hasher)
  }
}

private class EventChannelMessagesPigeonCodecReader: FlutterStandardReader {
>>>>>>> filtered-upstream/main:packages/pigeon/example/app/ios/Runner/EventChannelMessages.g.swift
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return PlatformEvent.fromListIntEvent(self.readValue() as! [Any?])
    case 130:
      return PlatformEvent.fromListStringEvent(self.readValue() as! [Any?])
    case 131:
      return PlatformEvent.fromListEmptyEvent(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class EventChannelMessagesGolubetsCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let childValue = value as? PlatformEvent, case .intEvent = childValue {
      super.writeByte(129)
      super.writeValue(childValue.toList())
    } else if let childValue = value as? PlatformEvent, case .stringEvent = childValue {
      super.writeByte(130)
      super.writeValue(childValue.toList())
    } else if let childValue = value as? PlatformEvent, case .emptyEvent = childValue {
      super.writeByte(131)
      super.writeValue(childValue.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class EventChannelMessagesGolubetsCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return EventChannelMessagesGolubetsCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return EventChannelMessagesGolubetsCodecWriter(data: data)
  }
}

class EventChannelMessagesGolubetsCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = EventChannelMessagesGolubetsCodec(
    readerWriter: EventChannelMessagesGolubetsCodecReaderWriter())
}

var eventChannelMessagesGolubetsMethodCodec = FlutterStandardMethodCodec(
  readerWriter: EventChannelMessagesGolubetsCodecReaderWriter())

private class GolubetsStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: GolubetsEventChannelWrapper<ReturnType>
  private var golubetsSink: GolubetsEventSink<ReturnType>? = nil

  init(wrapper: GolubetsEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    golubetsSink = GolubetsEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: golubetsSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    golubetsSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class GolubetsEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: GolubetsEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class GolubetsEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

class StreamEventsStreamHandler: GolubetsEventChannelWrapper<PlatformEvent> {
  static func register(
    with messenger: FlutterBinaryMessenger,
    instanceName: String = "",
    streamHandler: StreamEventsStreamHandler
  ) {
    var channelName =
      "dev.bayori.golubets.golubets_example_package.EventChannelMethods.streamEvents"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = GolubetsStreamHandler<PlatformEvent>(wrapper: streamHandler)
    let channel = FlutterEventChannel(
      name: channelName, binaryMessenger: messenger, codec: eventChannelMessagesGolubetsMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
