// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Golubets, do not edit directly.
// See also: https://pub.dev/packages/golubets

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
public final class GolubetsError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  public init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "GolubetsError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let golubetsError = error as? GolubetsError {
    return [
      golubetsError.code,
      golubetsError.message,
      golubetsError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> GolubetsError {
  return GolubetsError(
    code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.",
    details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsMessages(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashMessages(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8_0000_0000_0000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsMessages(lhsKey, rhsKey) {
          if deepEqualsMessages(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsMessages(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
<<<<<<< HEAD:packages/golubets/example/app/ios/Runner/Messages.g.swift
    // Any other type shouldn't be able to be used with golubetsets. File an issue if you find this to be untrue.
=======
>>>>>>> filtered-upstream/main:packages/pigeon/example/app/ios/Runner/Messages.g.swift
    return false
  }
}

func deepHashMessages(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashMessages(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashMessages(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashMessages(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashMessages(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashMessages(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}

public enum Code: Int {
  case one = 0
  case two = 1
}

/// Generated class from Golubets that represents data sent in messages.
public struct MessageData: Hashable {
  public init(
    name: String? = "Golub",
    description: String? = "Example description",
    code: Code = Code.one,
    data: [String: String] = [
      "hello": "world",
      "lorem": "ipsum",
      "golubets": "rocks",
    ]
  ) {
    self.name = name
    self.description = description
    self.code = code
    self.data = data
  }
  public var name: String?
  public var description: String?
  public var code: Code
  public var data: [String: String]

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ golubetsVar_list: [Any?]) -> MessageData? {
    let name: String? = nilOrValue(golubetsVar_list[0])
    let description: String? = nilOrValue(golubetsVar_list[1])
    let code = golubetsVar_list[2] as! Code
    let data = golubetsVar_list[3] as! [String: String]

    return MessageData(
      name: name,
      description: description,
      code: code,
      data: data
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      description,
      code,
      data,
    ]
  }
<<<<<<< HEAD:packages/golubets/example/app/ios/Runner/Messages.g.swift
  public static func == (lhs: MessageData, rhs: MessageData) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())
  }
  public func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
=======
  static func == (lhs: MessageData, rhs: MessageData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.name, rhs.name)
      && deepEqualsMessages(lhs.description, rhs.description)
      && deepEqualsMessages(lhs.code, rhs.code) && deepEqualsMessages(lhs.data, rhs.data)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MessageData")
    deepHashMessages(value: name, hasher: &hasher)
    deepHashMessages(value: description, hasher: &hasher)
    deepHashMessages(value: code, hasher: &hasher)
    deepHashMessages(value: data, hasher: &hasher)
>>>>>>> filtered-upstream/main:packages/pigeon/example/app/ios/Runner/Messages.g.swift
  }
}

private class MessagesGolubetsCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return Code(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return MessageData.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesGolubetsCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? Code {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? MessageData {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesGolubetsCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesGolubetsCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesGolubetsCodecWriter(data: data)
  }
}

class MessagesGolubetsCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesGolubetsCodec(readerWriter: MessagesGolubetsCodecReaderWriter())
}

/// Generated protocol from Golubets that represents a handler of messages from Flutter.
public protocol ExampleHostApi {
  func getHostLanguage() throws -> String
  func add(_ a: Int64, to b: Int64) throws -> Int64
  func sendMessage(message: MessageData, completion: @escaping (Result<Bool, Error>) -> Void)
  func sendMessageModernAsync(message: MessageData) async -> Bool
  func sendMessageModernAsyncThrows(message: MessageData) async throws -> Bool
}

/// Generated setup class from Golubets to handle messages through the `binaryMessenger`.
public class ExampleHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesGolubetsCodec.shared }
  /// Sets up an instance of `ExampleHostApi` to handle messages through the `binaryMessenger`.
  public static func setUp(
    binaryMessenger: FlutterBinaryMessenger, api: ExampleHostApi?, messageChannelSuffix: String = ""
  ) {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    #if os(iOS)
      let taskQueue = binaryMessenger.makeBackgroundTaskQueue?()
    #else
      let taskQueue: FlutterTaskQueue? = nil
    #endif
    let getHostLanguageChannel = FlutterBasicMessageChannel(
      name:
        "dev.bayori.golubets.golubets_example_package.ExampleHostApi.getHostLanguage\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getHostLanguageChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getHostLanguage()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getHostLanguageChannel.setMessageHandler(nil)
    }
    let addChannel = FlutterBasicMessageChannel(
      name: "dev.bayori.golubets.golubets_example_package.ExampleHostApi.add\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let aArg = args[0] as! Int64
        let bArg = args[1] as! Int64
        do {
          let result = try api.add(aArg, to: bArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      addChannel.setMessageHandler(nil)
    }
    let sendMessageChannel = FlutterBasicMessageChannel(
      name:
        "dev.bayori.golubets.golubets_example_package.ExampleHostApi.sendMessage\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendMessageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let messageArg = args[0] as! MessageData
        api.sendMessage(message: messageArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      sendMessageChannel.setMessageHandler(nil)
    }
    let sendMessageModernAsyncChannel =
      taskQueue == nil
      ? FlutterBasicMessageChannel(
        name:
          "dev.bayori.golubets.golubets_example_package.ExampleHostApi.sendMessageModernAsync\(channelSuffix)",
        binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(
        name:
          "dev.bayori.golubets.golubets_example_package.ExampleHostApi.sendMessageModernAsync\(channelSuffix)",
        binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      sendMessageModernAsyncChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let messageArg = args[0] as! MessageData
        Task {
          let result = await api.sendMessageModernAsync(message: messageArg)
          reply(wrapResult(result))
        }
      }
    } else {
      sendMessageModernAsyncChannel.setMessageHandler(nil)
    }
    let sendMessageModernAsyncThrowsChannel =
      taskQueue == nil
      ? FlutterBasicMessageChannel(
        name:
          "dev.bayori.golubets.golubets_example_package.ExampleHostApi.sendMessageModernAsyncThrows\(channelSuffix)",
        binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(
        name:
          "dev.bayori.golubets.golubets_example_package.ExampleHostApi.sendMessageModernAsyncThrows\(channelSuffix)",
        binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      sendMessageModernAsyncThrowsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let messageArg = args[0] as! MessageData
        Task {
          do {
            let result = try await api.sendMessageModernAsyncThrows(message: messageArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      sendMessageModernAsyncThrowsChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Golubets that represents Flutter messages that can be called from Swift.
public protocol MessageFlutterApiProtocol {
  func flutterMethod(
    aString aStringArg: String?, completion: @escaping (Result<String, GolubetsError>) -> Void)
}
public class MessageFlutterApi: MessageFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  public init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesGolubetsCodec {
    return MessagesGolubetsCodec.shared
  }
  public func flutterMethod(
    aString aStringArg: String?, completion: @escaping (Result<String, GolubetsError>) -> Void
  ) {
    let channelName: String =
      "dev.bayori.golubets.golubets_example_package.MessageFlutterApi.flutterMethod\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([aStringArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(GolubetsError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(
          .failure(
            GolubetsError(
              code: "null-error",
              message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! String
        completion(.success(result))
      }
    }
  }
}
