// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Golub, do not edit directly.
// See also: https://pub.dev/packages/golub

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_

#include <flutter_linux/flutter_linux.h>

G_BEGIN_DECLS

/**
 * GolubExamplePackageCode:
 * GOLUB_EXAMPLE_PACKAGE_CODE_ONE:
 * GOLUB_EXAMPLE_PACKAGE_CODE_TWO:
 *
 */
typedef enum {
  GOLUB_EXAMPLE_PACKAGE_CODE_ONE = 0,
  GOLUB_EXAMPLE_PACKAGE_CODE_TWO = 1
} GolubExamplePackageCode;

/**
 * GolubExamplePackageMessageData:
 *
 */

G_DECLARE_FINAL_TYPE(GolubExamplePackageMessageData,
                     golub_example_package_message_data, GOLUB_EXAMPLE_PACKAGE,
                     MESSAGE_DATA, GObject)

/**
 * golub_example_package_message_data_new:
 * name: field in this object.
 * description: field in this object.
 * code: field in this object.
 * data: field in this object.
 *
 * Creates a new #MessageData object.
 *
 * Returns: a new #GolubExamplePackageMessageData
 */
GolubExamplePackageMessageData* golub_example_package_message_data_new(
    const gchar* name, const gchar* description, GolubExamplePackageCode code,
    FlValue* data);

/**
 * golub_example_package_message_data_get_name
 * @object: a #GolubExamplePackageMessageData.
 *
 * Gets the value of the name field of @object.
 *
 * Returns: the field value.
 */
const gchar* golub_example_package_message_data_get_name(
    GolubExamplePackageMessageData* object);

/**
 * golub_example_package_message_data_get_description
 * @object: a #GolubExamplePackageMessageData.
 *
 * Gets the value of the description field of @object.
 *
 * Returns: the field value.
 */
const gchar* golub_example_package_message_data_get_description(
    GolubExamplePackageMessageData* object);

/**
 * golub_example_package_message_data_get_code
 * @object: a #GolubExamplePackageMessageData.
 *
 * Gets the value of the code field of @object.
 *
 * Returns: the field value.
 */
GolubExamplePackageCode golub_example_package_message_data_get_code(
    GolubExamplePackageMessageData* object);

/**
 * golub_example_package_message_data_get_data
 * @object: a #GolubExamplePackageMessageData.
 *
 * Gets the value of the data field of @object.
 *
 * Returns: the field value.
 */
FlValue* golub_example_package_message_data_get_data(
    GolubExamplePackageMessageData* object);

G_DECLARE_FINAL_TYPE(GolubExamplePackageGolubMessageCodec,
                     golub_example_package_golub_message_codec,
                     GOLUB_EXAMPLE_PACKAGE, GOLUB_MESSAGE_CODEC,
                     FlStandardMessageCodec)

/**
 * Custom type ID constants:
 *
 * Constants used to identify custom types in the codec.
 * They are used in the codec to encode and decode custom types.
 * They may be used in custom object creation functions to identify the type.
 */
extern const int golub_example_package_code_type_id;
extern const int golub_example_package_message_data_type_id;

G_DECLARE_FINAL_TYPE(GolubExamplePackageExampleHostApi,
                     golub_example_package_example_host_api,
                     GOLUB_EXAMPLE_PACKAGE, EXAMPLE_HOST_API, GObject)

G_DECLARE_FINAL_TYPE(GolubExamplePackageExampleHostApiResponseHandle,
                     golub_example_package_example_host_api_response_handle,
                     GOLUB_EXAMPLE_PACKAGE, EXAMPLE_HOST_API_RESPONSE_HANDLE,
                     GObject)

G_DECLARE_FINAL_TYPE(
    GolubExamplePackageExampleHostApiGetHostLanguageResponse,
    golub_example_package_example_host_api_get_host_language_response,
    GOLUB_EXAMPLE_PACKAGE, EXAMPLE_HOST_API_GET_HOST_LANGUAGE_RESPONSE, GObject)

/**
 * golub_example_package_example_host_api_get_host_language_response_new:
 *
 * Creates a new response to ExampleHostApi.getHostLanguage.
 *
 * Returns: a new #GolubExamplePackageExampleHostApiGetHostLanguageResponse
 */
GolubExamplePackageExampleHostApiGetHostLanguageResponse*
golub_example_package_example_host_api_get_host_language_response_new(
    const gchar* return_value);

/**
 * golub_example_package_example_host_api_get_host_language_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to ExampleHostApi.getHostLanguage.
 *
 * Returns: a new #GolubExamplePackageExampleHostApiGetHostLanguageResponse
 */
GolubExamplePackageExampleHostApiGetHostLanguageResponse*
golub_example_package_example_host_api_get_host_language_response_new_error(
    const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(GolubExamplePackageExampleHostApiAddResponse,
                     golub_example_package_example_host_api_add_response,
                     GOLUB_EXAMPLE_PACKAGE, EXAMPLE_HOST_API_ADD_RESPONSE,
                     GObject)

/**
 * golub_example_package_example_host_api_add_response_new:
 *
 * Creates a new response to ExampleHostApi.add.
 *
 * Returns: a new #GolubExamplePackageExampleHostApiAddResponse
 */
GolubExamplePackageExampleHostApiAddResponse*
golub_example_package_example_host_api_add_response_new(int64_t return_value);

/**
 * golub_example_package_example_host_api_add_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to ExampleHostApi.add.
 *
 * Returns: a new #GolubExamplePackageExampleHostApiAddResponse
 */
GolubExamplePackageExampleHostApiAddResponse*
golub_example_package_example_host_api_add_response_new_error(
    const gchar* code, const gchar* message, FlValue* details);

/**
 * GolubExamplePackageExampleHostApiVTable:
 *
 * Table of functions exposed by ExampleHostApi to be implemented by the API
 * provider.
 */
typedef struct {
  GolubExamplePackageExampleHostApiGetHostLanguageResponse* (
      *get_host_language)(gpointer user_data);
  GolubExamplePackageExampleHostApiAddResponse* (*add)(int64_t a, int64_t b,
                                                       gpointer user_data);
  void (*send_message)(
      GolubExamplePackageMessageData* message,
      GolubExamplePackageExampleHostApiResponseHandle* response_handle,
      gpointer user_data);
  void (*send_message_modern_async)(
      GolubExamplePackageMessageData* message,
      GolubExamplePackageExampleHostApiResponseHandle* response_handle,
      gpointer user_data);
  void (*send_message_modern_async_throws)(
      GolubExamplePackageMessageData* message,
      GolubExamplePackageExampleHostApiResponseHandle* response_handle,
      gpointer user_data);
} GolubExamplePackageExampleHostApiVTable;

/**
 * golub_example_package_example_host_api_set_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 * @vtable: implementations of the methods in this API.
 * @user_data: (closure): user data to pass to the functions in @vtable.
 * @user_data_free_func: (allow-none): a function which gets called to free
 * @user_data, or %NULL.
 *
 * Connects the method handlers in the ExampleHostApi API.
 */
void golub_example_package_example_host_api_set_method_handlers(
    FlBinaryMessenger* messenger, const gchar* suffix,
    const GolubExamplePackageExampleHostApiVTable* vtable, gpointer user_data,
    GDestroyNotify user_data_free_func);

/**
 * golub_example_package_example_host_api_clear_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Clears the method handlers in the ExampleHostApi API.
 */
void golub_example_package_example_host_api_clear_method_handlers(
    FlBinaryMessenger* messenger, const gchar* suffix);

/**
 * golub_example_package_example_host_api_respond_send_message:
 * @response_handle: a #GolubExamplePackageExampleHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to ExampleHostApi.sendMessage.
 */
void golub_example_package_example_host_api_respond_send_message(
    GolubExamplePackageExampleHostApiResponseHandle* response_handle,
    gboolean return_value);

/**
 * golub_example_package_example_host_api_respond_error_send_message:
 * @response_handle: a #GolubExamplePackageExampleHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to ExampleHostApi.sendMessage.
 */
void golub_example_package_example_host_api_respond_error_send_message(
    GolubExamplePackageExampleHostApiResponseHandle* response_handle,
    const gchar* code, const gchar* message, FlValue* details);

/**
 * golub_example_package_example_host_api_respond_send_message_modern_async:
 * @response_handle: a #GolubExamplePackageExampleHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to ExampleHostApi.sendMessageModernAsync.
 */
void golub_example_package_example_host_api_respond_send_message_modern_async(
    GolubExamplePackageExampleHostApiResponseHandle* response_handle,
    gboolean return_value);

/**
 * golub_example_package_example_host_api_respond_error_send_message_modern_async:
 * @response_handle: a #GolubExamplePackageExampleHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to ExampleHostApi.sendMessageModernAsync.
 */
void golub_example_package_example_host_api_respond_error_send_message_modern_async(
    GolubExamplePackageExampleHostApiResponseHandle* response_handle,
    const gchar* code, const gchar* message, FlValue* details);

/**
 * golub_example_package_example_host_api_respond_send_message_modern_async_throws:
 * @response_handle: a #GolubExamplePackageExampleHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to ExampleHostApi.sendMessageModernAsyncThrows.
 */
void golub_example_package_example_host_api_respond_send_message_modern_async_throws(
    GolubExamplePackageExampleHostApiResponseHandle* response_handle,
    gboolean return_value);

/**
 * golub_example_package_example_host_api_respond_error_send_message_modern_async_throws:
 * @response_handle: a #GolubExamplePackageExampleHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to ExampleHostApi.sendMessageModernAsyncThrows.
 */
void golub_example_package_example_host_api_respond_error_send_message_modern_async_throws(
    GolubExamplePackageExampleHostApiResponseHandle* response_handle,
    const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(
    GolubExamplePackageMessageFlutterApiFlutterMethodResponse,
    golub_example_package_message_flutter_api_flutter_method_response,
    GOLUB_EXAMPLE_PACKAGE, MESSAGE_FLUTTER_API_FLUTTER_METHOD_RESPONSE, GObject)

/**
 * golub_example_package_message_flutter_api_flutter_method_response_is_error:
 * @response: a #GolubExamplePackageMessageFlutterApiFlutterMethodResponse.
 *
 * Checks if a response to MessageFlutterApi.flutterMethod is an error.
 *
 * Returns: a %TRUE if this response is an error.
 */
gboolean
golub_example_package_message_flutter_api_flutter_method_response_is_error(
    GolubExamplePackageMessageFlutterApiFlutterMethodResponse* response);

/**
 * golub_example_package_message_flutter_api_flutter_method_response_get_error_code:
 * @response: a #GolubExamplePackageMessageFlutterApiFlutterMethodResponse.
 *
 * Get the error code for this response.
 *
 * Returns: an error code or %NULL if not an error.
 */
const gchar*
golub_example_package_message_flutter_api_flutter_method_response_get_error_code(
    GolubExamplePackageMessageFlutterApiFlutterMethodResponse* response);

/**
 * golub_example_package_message_flutter_api_flutter_method_response_get_error_message:
 * @response: a #GolubExamplePackageMessageFlutterApiFlutterMethodResponse.
 *
 * Get the error message for this response.
 *
 * Returns: an error message.
 */
const gchar*
golub_example_package_message_flutter_api_flutter_method_response_get_error_message(
    GolubExamplePackageMessageFlutterApiFlutterMethodResponse* response);

/**
 * golub_example_package_message_flutter_api_flutter_method_response_get_error_details:
 * @response: a #GolubExamplePackageMessageFlutterApiFlutterMethodResponse.
 *
 * Get the error details for this response.
 *
 * Returns: (allow-none): an error details or %NULL.
 */
FlValue*
golub_example_package_message_flutter_api_flutter_method_response_get_error_details(
    GolubExamplePackageMessageFlutterApiFlutterMethodResponse* response);

/**
 * golub_example_package_message_flutter_api_flutter_method_response_get_return_value:
 * @response: a #GolubExamplePackageMessageFlutterApiFlutterMethodResponse.
 *
 * Get the return value for this response.
 *
 * Returns: a return value.
 */
const gchar*
golub_example_package_message_flutter_api_flutter_method_response_get_return_value(
    GolubExamplePackageMessageFlutterApiFlutterMethodResponse* response);

/**
 * GolubExamplePackageMessageFlutterApi:
 *
 */

G_DECLARE_FINAL_TYPE(GolubExamplePackageMessageFlutterApi,
                     golub_example_package_message_flutter_api,
                     GOLUB_EXAMPLE_PACKAGE, MESSAGE_FLUTTER_API, GObject)

/**
 * golub_example_package_message_flutter_api_new:
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Creates a new object to access the MessageFlutterApi API.
 *
 * Returns: a new #GolubExamplePackageMessageFlutterApi
 */
GolubExamplePackageMessageFlutterApi*
golub_example_package_message_flutter_api_new(FlBinaryMessenger* messenger,
                                              const gchar* suffix);

/**
 * golub_example_package_message_flutter_api_flutter_method:
 * @api: a #GolubExamplePackageMessageFlutterApi.
 * @a_string: (allow-none): parameter for this method.
 * @cancellable: (allow-none): a #GCancellable or %NULL.
 * @callback: (scope async): (allow-none): a #GAsyncReadyCallback to call when
 * the call is complete or %NULL to ignore the response.
 * @user_data: (closure): user data to pass to @callback.
 *
 */
void golub_example_package_message_flutter_api_flutter_method(
    GolubExamplePackageMessageFlutterApi* api, const gchar* a_string,
    GCancellable* cancellable, GAsyncReadyCallback callback,
    gpointer user_data);

/**
 * golub_example_package_message_flutter_api_flutter_method_finish:
 * @api: a #GolubExamplePackageMessageFlutterApi.
 * @result: a #GAsyncResult.
 * @error: (allow-none): #GError location to store the error occurring, or %NULL
 * to ignore.
 *
 * Completes a golub_example_package_message_flutter_api_flutter_method() call.
 *
 * Returns: a #GolubExamplePackageMessageFlutterApiFlutterMethodResponse or
 * %NULL on error.
 */
GolubExamplePackageMessageFlutterApiFlutterMethodResponse*
golub_example_package_message_flutter_api_flutter_method_finish(
    GolubExamplePackageMessageFlutterApi* api, GAsyncResult* result,
    GError** error);

G_END_DECLS

#endif  // PIGEON_MESSAGES_G_H_
