// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Golubets, do not edit directly.
// See also: https://pub.dev/packages/golubets

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_

#include <flutter_linux/flutter_linux.h>

G_BEGIN_DECLS

/**
 * GolubetsExamplePackageCode:
 * GOLUBETS_EXAMPLE_PACKAGE_CODE_ONE:
 * GOLUBETS_EXAMPLE_PACKAGE_CODE_TWO:
 *
 */
typedef enum {
  GOLUBETS_EXAMPLE_PACKAGE_CODE_ONE = 0,
  GOLUBETS_EXAMPLE_PACKAGE_CODE_TWO = 1
} GolubetsExamplePackageCode;

/**
 * GolubetsExamplePackageMessageData:
 *
 */

G_DECLARE_FINAL_TYPE(GolubetsExamplePackageMessageData,
                     golubets_example_package_message_data,
                     GOLUBETS_EXAMPLE_PACKAGE, MESSAGE_DATA, GObject)

/**
 * golubets_example_package_message_data_new:
 * name: field in this object.
 * description: field in this object.
 * code: field in this object.
 * data: field in this object.
 *
 * Creates a new #MessageData object.
 *
 * Returns: a new #GolubetsExamplePackageMessageData
 */
GolubetsExamplePackageMessageData* golubets_example_package_message_data_new(
    const gchar* name, const gchar* description,
    GolubetsExamplePackageCode code, FlValue* data);

/**
 * golubets_example_package_message_data_get_name
 * @object: a #GolubetsExamplePackageMessageData.
 *
 * Gets the value of the name field of @object.
 *
 * Returns: the field value.
 */
const gchar* golubets_example_package_message_data_get_name(
    GolubetsExamplePackageMessageData* object);

/**
 * golubets_example_package_message_data_get_description
 * @object: a #GolubetsExamplePackageMessageData.
 *
 * Gets the value of the description field of @object.
 *
 * Returns: the field value.
 */
const gchar* golubets_example_package_message_data_get_description(
    GolubetsExamplePackageMessageData* object);

/**
 * golubets_example_package_message_data_get_code
 * @object: a #GolubetsExamplePackageMessageData.
 *
 * Gets the value of the code field of @object.
 *
 * Returns: the field value.
 */
GolubetsExamplePackageCode golubets_example_package_message_data_get_code(
    GolubetsExamplePackageMessageData* object);

/**
 * golubets_example_package_message_data_get_data
 * @object: a #GolubetsExamplePackageMessageData.
 *
 * Gets the value of the data field of @object.
 *
 * Returns: the field value.
 */
FlValue* golubets_example_package_message_data_get_data(
    GolubetsExamplePackageMessageData* object);

G_DECLARE_FINAL_TYPE(GolubetsExamplePackageGolubMessageCodec,
                     golubets_example_package_golub_message_codec,
                     GOLUBETS_EXAMPLE_PACKAGE, GOLUB_MESSAGE_CODEC,
                     FlStandardMessageCodec)

/**
 * Custom type ID constants:
 *
 * Constants used to identify custom types in the codec.
 * They are used in the codec to encode and decode custom types.
 * They may be used in custom object creation functions to identify the type.
 */
extern const int golubets_example_package_code_type_id;
extern const int golubets_example_package_message_data_type_id;

G_DECLARE_FINAL_TYPE(GolubetsExamplePackageExampleHostApi,
                     golubets_example_package_example_host_api,
                     GOLUBETS_EXAMPLE_PACKAGE, EXAMPLE_HOST_API, GObject)

G_DECLARE_FINAL_TYPE(GolubetsExamplePackageExampleHostApiResponseHandle,
                     golubets_example_package_example_host_api_response_handle,
                     GOLUBETS_EXAMPLE_PACKAGE, EXAMPLE_HOST_API_RESPONSE_HANDLE,
                     GObject)

G_DECLARE_FINAL_TYPE(
    GolubetsExamplePackageExampleHostApiGetHostLanguageResponse,
    golubets_example_package_example_host_api_get_host_language_response,
    GOLUBETS_EXAMPLE_PACKAGE, EXAMPLE_HOST_API_GET_HOST_LANGUAGE_RESPONSE,
    GObject)

/**
 * golubets_example_package_example_host_api_get_host_language_response_new:
 *
 * Creates a new response to ExampleHostApi.getHostLanguage.
 *
 * Returns: a new #GolubetsExamplePackageExampleHostApiGetHostLanguageResponse
 */
GolubetsExamplePackageExampleHostApiGetHostLanguageResponse*
golubets_example_package_example_host_api_get_host_language_response_new(
    const gchar* return_value);

/**
 * golubets_example_package_example_host_api_get_host_language_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to ExampleHostApi.getHostLanguage.
 *
 * Returns: a new #GolubetsExamplePackageExampleHostApiGetHostLanguageResponse
 */
GolubetsExamplePackageExampleHostApiGetHostLanguageResponse*
golubets_example_package_example_host_api_get_host_language_response_new_error(
    const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(GolubetsExamplePackageExampleHostApiAddResponse,
                     golubets_example_package_example_host_api_add_response,
                     GOLUBETS_EXAMPLE_PACKAGE, EXAMPLE_HOST_API_ADD_RESPONSE,
                     GObject)

/**
 * golubets_example_package_example_host_api_add_response_new:
 *
 * Creates a new response to ExampleHostApi.add.
 *
 * Returns: a new #GolubetsExamplePackageExampleHostApiAddResponse
 */
GolubetsExamplePackageExampleHostApiAddResponse*
golubets_example_package_example_host_api_add_response_new(
    int64_t return_value);

/**
 * golubets_example_package_example_host_api_add_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to ExampleHostApi.add.
 *
 * Returns: a new #GolubetsExamplePackageExampleHostApiAddResponse
 */
GolubetsExamplePackageExampleHostApiAddResponse*
golubets_example_package_example_host_api_add_response_new_error(
    const gchar* code, const gchar* message, FlValue* details);

/**
 * GolubetsExamplePackageExampleHostApiVTable:
 *
 * Table of functions exposed by ExampleHostApi to be implemented by the API
 * provider.
 */
typedef struct {
  GolubetsExamplePackageExampleHostApiGetHostLanguageResponse* (
      *get_host_language)(gpointer user_data);
  GolubetsExamplePackageExampleHostApiAddResponse* (*add)(int64_t a, int64_t b,
                                                          gpointer user_data);
  void (*send_message)(
      GolubetsExamplePackageMessageData* message,
      GolubetsExamplePackageExampleHostApiResponseHandle* response_handle,
      gpointer user_data);
  void (*send_message_modern_async)(
      GolubetsExamplePackageMessageData* message,
      GolubetsExamplePackageExampleHostApiResponseHandle* response_handle,
      gpointer user_data);
  void (*send_message_modern_async_throws)(
      GolubetsExamplePackageMessageData* message,
      GolubetsExamplePackageExampleHostApiResponseHandle* response_handle,
      gpointer user_data);
} GolubetsExamplePackageExampleHostApiVTable;

/**
 * golubets_example_package_example_host_api_set_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 * @vtable: implementations of the methods in this API.
 * @user_data: (closure): user data to pass to the functions in @vtable.
 * @user_data_free_func: (allow-none): a function which gets called to free
 * @user_data, or %NULL.
 *
 * Connects the method handlers in the ExampleHostApi API.
 */
void golubets_example_package_example_host_api_set_method_handlers(
    FlBinaryMessenger* messenger, const gchar* suffix,
    const GolubetsExamplePackageExampleHostApiVTable* vtable,
    gpointer user_data, GDestroyNotify user_data_free_func);

/**
 * golubets_example_package_example_host_api_clear_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Clears the method handlers in the ExampleHostApi API.
 */
void golubets_example_package_example_host_api_clear_method_handlers(
    FlBinaryMessenger* messenger, const gchar* suffix);

/**
 * golubets_example_package_example_host_api_respond_send_message:
 * @response_handle: a #GolubetsExamplePackageExampleHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to ExampleHostApi.sendMessage.
 */
void golubets_example_package_example_host_api_respond_send_message(
    GolubetsExamplePackageExampleHostApiResponseHandle* response_handle,
    gboolean return_value);

/**
 * golubets_example_package_example_host_api_respond_error_send_message:
 * @response_handle: a #GolubetsExamplePackageExampleHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to ExampleHostApi.sendMessage.
 */
void golubets_example_package_example_host_api_respond_error_send_message(
    GolubetsExamplePackageExampleHostApiResponseHandle* response_handle,
    const gchar* code, const gchar* message, FlValue* details);

/**
 * golubets_example_package_example_host_api_respond_send_message_modern_async:
 * @response_handle: a #GolubetsExamplePackageExampleHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to ExampleHostApi.sendMessageModernAsync.
 */
void golubets_example_package_example_host_api_respond_send_message_modern_async(
    GolubetsExamplePackageExampleHostApiResponseHandle* response_handle,
    gboolean return_value);

/**
 * golubets_example_package_example_host_api_respond_error_send_message_modern_async:
 * @response_handle: a #GolubetsExamplePackageExampleHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to ExampleHostApi.sendMessageModernAsync.
 */
void golubets_example_package_example_host_api_respond_error_send_message_modern_async(
    GolubetsExamplePackageExampleHostApiResponseHandle* response_handle,
    const gchar* code, const gchar* message, FlValue* details);

/**
 * golubets_example_package_example_host_api_respond_send_message_modern_async_throws:
 * @response_handle: a #GolubetsExamplePackageExampleHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to ExampleHostApi.sendMessageModernAsyncThrows.
 */
void golubets_example_package_example_host_api_respond_send_message_modern_async_throws(
    GolubetsExamplePackageExampleHostApiResponseHandle* response_handle,
    gboolean return_value);

/**
 * golubets_example_package_example_host_api_respond_error_send_message_modern_async_throws:
 * @response_handle: a #GolubetsExamplePackageExampleHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to ExampleHostApi.sendMessageModernAsyncThrows.
 */
void golubets_example_package_example_host_api_respond_error_send_message_modern_async_throws(
    GolubetsExamplePackageExampleHostApiResponseHandle* response_handle,
    const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(
    GolubetsExamplePackageMessageFlutterApiFlutterMethodResponse,
    golubets_example_package_message_flutter_api_flutter_method_response,
    GOLUBETS_EXAMPLE_PACKAGE, MESSAGE_FLUTTER_API_FLUTTER_METHOD_RESPONSE,
    GObject)

/**
 * golubets_example_package_message_flutter_api_flutter_method_response_is_error:
 * @response: a #GolubetsExamplePackageMessageFlutterApiFlutterMethodResponse.
 *
 * Checks if a response to MessageFlutterApi.flutterMethod is an error.
 *
 * Returns: a %TRUE if this response is an error.
 */
gboolean
golubets_example_package_message_flutter_api_flutter_method_response_is_error(
    GolubetsExamplePackageMessageFlutterApiFlutterMethodResponse* response);

/**
 * golubets_example_package_message_flutter_api_flutter_method_response_get_error_code:
 * @response: a #GolubetsExamplePackageMessageFlutterApiFlutterMethodResponse.
 *
 * Get the error code for this response.
 *
 * Returns: an error code or %NULL if not an error.
 */
const gchar*
golubets_example_package_message_flutter_api_flutter_method_response_get_error_code(
    GolubetsExamplePackageMessageFlutterApiFlutterMethodResponse* response);

/**
 * golubets_example_package_message_flutter_api_flutter_method_response_get_error_message:
 * @response: a #GolubetsExamplePackageMessageFlutterApiFlutterMethodResponse.
 *
 * Get the error message for this response.
 *
 * Returns: an error message.
 */
const gchar*
golubets_example_package_message_flutter_api_flutter_method_response_get_error_message(
    GolubetsExamplePackageMessageFlutterApiFlutterMethodResponse* response);

/**
 * golubets_example_package_message_flutter_api_flutter_method_response_get_error_details:
 * @response: a #GolubetsExamplePackageMessageFlutterApiFlutterMethodResponse.
 *
 * Get the error details for this response.
 *
 * Returns: (allow-none): an error details or %NULL.
 */
FlValue*
golubets_example_package_message_flutter_api_flutter_method_response_get_error_details(
    GolubetsExamplePackageMessageFlutterApiFlutterMethodResponse* response);

/**
 * golubets_example_package_message_flutter_api_flutter_method_response_get_return_value:
 * @response: a #GolubetsExamplePackageMessageFlutterApiFlutterMethodResponse.
 *
 * Get the return value for this response.
 *
 * Returns: a return value.
 */
const gchar*
golubets_example_package_message_flutter_api_flutter_method_response_get_return_value(
    GolubetsExamplePackageMessageFlutterApiFlutterMethodResponse* response);

/**
 * GolubetsExamplePackageMessageFlutterApi:
 *
 */

G_DECLARE_FINAL_TYPE(GolubetsExamplePackageMessageFlutterApi,
                     golubets_example_package_message_flutter_api,
                     GOLUBETS_EXAMPLE_PACKAGE, MESSAGE_FLUTTER_API, GObject)

/**
 * golubets_example_package_message_flutter_api_new:
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Creates a new object to access the MessageFlutterApi API.
 *
 * Returns: a new #GolubetsExamplePackageMessageFlutterApi
 */
GolubetsExamplePackageMessageFlutterApi*
golubets_example_package_message_flutter_api_new(FlBinaryMessenger* messenger,
                                                 const gchar* suffix);

/**
 * golubets_example_package_message_flutter_api_flutter_method:
 * @api: a #GolubetsExamplePackageMessageFlutterApi.
 * @a_string: (allow-none): parameter for this method.
 * @cancellable: (allow-none): a #GCancellable or %NULL.
 * @callback: (scope async): (allow-none): a #GAsyncReadyCallback to call when
 * the call is complete or %NULL to ignore the response.
 * @user_data: (closure): user data to pass to @callback.
 *
 */
void golubets_example_package_message_flutter_api_flutter_method(
    GolubetsExamplePackageMessageFlutterApi* api, const gchar* a_string,
    GCancellable* cancellable, GAsyncReadyCallback callback,
    gpointer user_data);

/**
 * golubets_example_package_message_flutter_api_flutter_method_finish:
 * @api: a #GolubetsExamplePackageMessageFlutterApi.
 * @result: a #GAsyncResult.
 * @error: (allow-none): #GError location to store the error occurring, or %NULL
 * to ignore.
 *
 * Completes a golubets_example_package_message_flutter_api_flutter_method()
 * call.
 *
 * Returns: a #GolubetsExamplePackageMessageFlutterApiFlutterMethodResponse or
 * %NULL on error.
 */
GolubetsExamplePackageMessageFlutterApiFlutterMethodResponse*
golubets_example_package_message_flutter_api_flutter_method_finish(
    GolubetsExamplePackageMessageFlutterApi* api, GAsyncResult* result,
    GError** error);

G_END_DECLS

#endif  // PIGEON_MESSAGES_G_H_
