name: golubets_example_app
description: An example of using Golubets in an application.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  golubets:
    path: ../../
  integration_test:
    sdk: flutter
    # When depending on this package from a real application you should use:
    #   file_selector_windows: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.

flutter:
  uses-material-design: true
